Repository krisnasirait/One-Finance, pull requests merged in 2022-10, with the labels that each got.

#1 add mobile navigation
  .idea/discord.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/primetech/onefinance/MainActivity.kt
  app/src/main/java/com/primetech/onefinance/WalletFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_wallet.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#2 feat/splash_screen
  .gitignore
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/primetech/onefinance/presentation/branding/SplashScreenActivity.kt
  app/src/main/res/anim/above_num_animation.xml
  app/src/main/res/anim/below_num_animation.xml
  app/src/main/res/anim/bottom_animation.xml
  app/src/main/res/drawable/ic_num_above_one.png
  app/src/main/res/drawable/ic_num_below_one.png
  app/src/main/res/drawable/ic_one_finance.png
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/layout/fragment_wallet.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#4 added wallet layout in wallet_fragment
  .idea/misc.xml
  .idea/vcs.xml
  app/src/main/res/layout/fragment_wallet.xml
  app/src/main/res/layout/item_portofolio.xml
Labels: bug, enhancement

#8 working fragment_wallet
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/primetech/onefinance/WalletFragment.kt
  app/src/main/java/com/primetech/onefinance/wallet/WalletFragment.kt
  app/src/main/java/com/primetech/onefinance/wallet/portofolio/Portofolio.kt
  app/src/main/java/com/primetech/onefinance/wallet/portofolio/PortofolioAdapter.kt
  app/src/main/java/com/primetech/onefinance/wallet/tradehistory/TradeHistory.kt
  app/src/main/java/com/primetech/onefinance/wallet/tradehistory/TradeHistoryAdapter.kt
  app/src/main/res/layout/fragment_wallet.xml
  app/src/main/res/layout/item_portofolio.xml
  app/src/main/res/layout/item_trade_history.xml
  app/src/main/res/navigation/mobile_navigation.xml
Labels: bug, enhancement

#10 feat/market
  .idea/misc.xml
  app/src/main/java/com/primetech/onefinance/data/Utility.kt
  app/src/main/java/com/primetech/onefinance/data/model/Market.kt
  app/src/main/java/com/primetech/onefinance/presentation/auth/LoginActivity.kt
  app/src/main/java/com/primetech/onefinance/presentation/auth/SignUpActivity.kt
  app/src/main/java/com/primetech/onefinance/presentation/main/market/adapter/MarketAdapter.kt
  app/src/main/java/com/primetech/onefinance/presentation/main/market/view/MarketFragment.kt
  app/src/main/res/drawable/bitcoin.png
  app/src/main/res/drawable/ethereum.png
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/tron.png
  app/src/main/res/layout/fragment_market.xml
  app/src/main/res/layout/item_market.xml
  app/src/main/res/navigation/mobile_navigation.xml
Labels: enhancement

#11 changes on layout wallet
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/res/drawable/bg_bot_nav_bar.xml
  app/src/main/res/drawable/bg_porto_trade.xml
  app/src/main/res/drawable/bg_wallet.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_wallet.xml
  app/src/main/res/layout/item_portofolio.xml
  app/src/main/res/layout/item_trade_history.xml
Labels: bug, enhancement

#12 feat/search
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/primetech/onefinance/data/Utility.kt
  app/src/main/java/com/primetech/onefinance/presentation/auth/LoginActivity.kt
  app/src/main/java/com/primetech/onefinance/presentation/auth/SignUpActivity.kt
  app/src/main/java/com/primetech/onefinance/presentation/main/market/view/MarketFragment.kt
  app/src/main/java/com/primetech/onefinance/presentation/main/search/SearchActivity.kt
  app/src/main/res/drawable/ic_one_finance_grey.png
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/fragment_market.xml
  app/src/main/res/layout/item_market.xml
Labels: bug, documentation, enhancement

#13 added feature trade
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/primetech/onefinance/data/Utility.kt
  app/src/main/java/com/primetech/onefinance/presentation/main/detail/Detail.kt
  app/src/main/java/com/primetech/onefinance/presentation/main/detail/DetailActivity.kt
  app/src/main/java/com/primetech/onefinance/presentation/main/wallet/WalletFragment.kt
  app/src/main/java/com/primetech/onefinance/presentation/main/wallet/portofolio/Portofolio.kt
  app/src/main/java/com/primetech/onefinance/presentation/main/wallet/portofolio/PortofolioAdapter.kt
  app/src/main/java/com/primetech/onefinance/presentation/main/wallet/tradehistory/TradeHistory.kt
  app/src/main/java/com/primetech/onefinance/presentation/main/wallet/tradehistory/TradeHistoryAdapter.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/custom_buy_dialog.xml
  app/src/main/res/layout/custom_sell_dialog.xml
Labels: documentation, enhancement

#14 fix bug on utility data
  app/src/main/java/com/primetech/onefinance/data/Utility.kt
Labels: bug, enhancement
